=== sharamigo/php_webprojects/semesterarbeit/data/cinemamovies.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cinemamovies (movie)* >
<!ELEMENT movie (id, titel, original_title, produktionsland, duration, release_year, genre, director, screenwriter, music?, oscars, fsk, actors, movie_poster) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT titel (#PCDATA) >
<!ELEMENT original_title (#PCDATA) >
<!ELEMENT produktionsland (#PCDATA) >
<!ELEMENT duration (#PCDATA) >
<!ELEMENT release_year (#PCDATA) >
<!ELEMENT genre (#PCDATA) >
<!ELEMENT director (#PCDATA) >
<!ELEMENT screenwriter (#PCDATA) >
<!ELEMENT music (#PCDATA) >
<!ELEMENT oscars (#PCDATA) >
<!ELEMENT fsk (#PCDATA) >
<!ELEMENT actors (#PCDATA) >
<!ELEMENT movie_poster (#PCDATA) >

=== sharamigo/php_webprojects/semesterarbeit/data/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cinemamovies SYSTEM "cinemamovies.dtd">
<cinemamovies>
	<movie>
		<id>100</id>
		<titel>Star Wars: Episode I – Die dunkle Bedrohung</titel>
		<original_title>Star Wars: Episode I – The Phantom Menace</original_title>
		<produktionsland>USA</produktionsland>
		<duration>128</duration>
		<release_year>1999</release_year>
		<genre>Science-Fiction</genre>
		<director>George Lucas</director>
		<screenwriter>George Lucas</screenwriter>
		<music>John Williams</music>
		<oscars>0</oscars>
		<fsk>ab 12 Jahre</fsk>
		<actors>Liam Neeson: Qui-Gon Jinn
Ewan McGregor: Obi-Wan Kenobi
Natalie Portman: Königin Amidala (Padmé Naberrie)
Jake Lloyd: Anakin Skywalker
Pernilla August: Shmi Skywalker
Frank Oz: Yoda
Ian McDiarmid: Senator Palpatine (Darth Sidious)
Ray Park/Peter Serafinowicz (Stimme): Darth Maul
Hugh Quarshie: Captain Panaka
Ahmed Best: Jar Jar Binks
Anthony Daniels: C-3PO
Kenny Baker: R2-D2
Terence Stamp: Kanzler Valorum
Brian Blessed: Boss Nass
Andrew Secombe: Watto
Lewis Macleod: Sebulba
Silas Carson: Vizekönig Nute Gunray, Ki-Adi-Mundi, Lott Dodd
Samuel L. Jackson: Mace Windu
Keira Knightley: Sabé
</actors>
		<movie_poster>Star_Wars_Episode1-Poster.jpg</movie_poster>
	</movie>
	<movie>
		<id>125</id>
		<titel>Star Wars: Episode II – Angriff der Klonkrieger</titel>
		<original_title>Star Wars: Episode II – Attack of the Clones</original_title>
		<produktionsland>USA</produktionsland>
		<duration>137</duration>
		<release_year>2002</release_year>
		<genre>Science-Fiction</genre>
		<director>George Lucas</director>
		<screenwriter>George Lucas</screenwriter>
		<music>John Williams</music>
		<oscars>0</oscars>
		<fsk>ab 12 Jahre</fsk>
		<actors>Hayden Christensen: Anakin Skywalker
Ewan McGregor: Obi-Wan Kenobi
Natalie Portman: Senatorin Padmé Amidala
Christopher Lee: Count Dooku/Darth Tyranus
Samuel L. Jackson: Mace Windu
Frank Oz: Yoda
Ian McDiarmid: Kanzler Palpatine/Darth Sidious
Pernilla August: Shmi Skywalker-Lars
Temuera Morrison: Jango Fett, Klonsoldaten
Daniel Logan: Boba Fett
Jimmy Smits: Senator Bail Organa
Leeanna Walsman: Zam Wesell
Ahmed Best: Jar Jar Binks
Andy Secombe: Watto
Anthony Daniels: C-3PO
Silas Carson: Ki-Adi-Mundi, Vizekönig Nute Gunray
</actors>
		<movie_poster>star_wars_episode_two.jpg</movie_poster>
	</movie>
	<movie>
		<id>138</id>
		<titel>Der Herr der Ringe: Die Gefährten</titel>
		<original_title>The Lord of the Rings: The Fellowship of the Ring</original_title>
		<produktionsland>USA, Neuseeland</produktionsland>
		<duration>178</duration>
		<release_year>2001</release_year>
		<genre>Fantasy</genre>
		<director>Peter Jackson</director>
		<screenwriter>Fran Walsh, Philippa Boyens, Peter Jackson</screenwriter>
		<music>Howard Shore</music>
		<oscars>4</oscars>
		<fsk>ab 12 Jahre</fsk>
		<actors>Elijah Wood: Frodo Beutlin
Ian McKellen: Gandalf
Sean Astin: Samweis Gamdschie
Viggo Mortensen: Aragorn/Streicher
Liv Tyler: Arwen Undomiel
Sean Bean: Boromir
Orlando Bloom: Legolas
John Rhys-Davies: Gimli
Christopher Lee: Saruman
Dominic Monaghan: Meriadoc Brandybock
Billy Boyd: Peregrin Tuk
Cate Blanchett: Galadriel
Hugo Weaving: Elrond
Ian Holm: Bilbo Beutlin</actors>
		<movie_poster>herr-ringe-gefaehrten.jpg</movie_poster>
	</movie>
	<movie>
		<id>139</id>
		<titel>Der Herr der Ringe: Die Zwei Türme</titel>
		<original_title>The Lord of the Rings: The Two Towers</original_title>
		<produktionsland>USA, Neuseeland</produktionsland>
		<duration>179</duration>
		<release_year>2002</release_year>
		<genre>Fantasy</genre>
		<director>Peter Jackson</director>
		<screenwriter>Fran Walsh, Philippa Boyens, Peter Jackson</screenwriter>
		<music>Howard Shore</music>
		<oscars>2</oscars>
		<fsk>ab 12 Jahre</fsk>
		<actors>Elijah Wood: Frodo Beutlin
Sean Astin: Samweis Gamdschie
Viggo Mortensen: Aragorn
Ian McKellen: Gandalf
Dominic Monaghan: Meriadoc Brandybock
Billy Boyd: Peregrin Tuk
Orlando Bloom: Legolas
John Rhys-Davies: Gimli/Baumbart (Stimme)
Andy Serkis: Gollum/Sméagol
Christopher Lee: Saruman
Bernard Hill: Théoden
Miranda Otto: Éowyn
Karl Urban: Éomer
Brad Dourif: Gríma Schlangenzunge
Liv Tyler: Arwen Undomiel
Hugo Weaving: Elrond
David Wenham: Faramir
Cate Blanchett: Galadriel</actors>
		<movie_poster>DerHerrderRingeDiezweiTurme.jpg</movie_poster>
	</movie>
	<movie>
		<id>140</id>
		<titel>Der Herr der Ringe: Die Rückkehr des Königs</titel>
		<original_title>The Lord of the Rings: The Return of the King</original_title>
		<produktionsland>USA, Neuseeland</produktionsland>
		<duration>201</duration>
		<release_year>2003</release_year>
		<genre>Fantasy</genre>
		<director>Peter Jackson</director>
		<screenwriter>Fran Walsh, Philippa Boyens, Peter Jackson</screenwriter>
		<music>Howard Shore</music>
		<oscars>11</oscars>
		<fsk>ab 12 Jahre</fsk>
		<actors>Viggo Mortensen: Aragorn / Elessar
Liv Tyler: Arwen Undómiel
Ian McKellen: Gandalf
Christopher Lee: Saruman[4]
Sean Bean: Boromir
Ian Holm: Bilbo Beutlin
Marton Csokas: Celeborn
John Noble: Denethor
Hugo Weaving: Elrond
Karl Urban: Éomer
Miranda Otto: Éowyn
David Wenham: Faramir
Elijah Wood: Frodo Beutlin
Cate Blanchett: Galadriel
John Rhys-Davies: Gimli / Baumbart (Stimme)
Brad Dourif: Grima Schlangenzunge
Andy Serkis: Gollum / Sméagol
Lawrence Makoare: Gothmog / Hexenkönig
Paul Norell: König der Toten
Orlando Bloom: Legolas
Dominic Monaghan: Meriadoc Brandybock
Billy Boyd: Peregrin Tuk
Sean Astin: Samweis Gamdschie
Alan Howard: Stimme Saurons
Ian Hughes: Irolas
Bernard Hill: Théoden</actors>
		<movie_poster>Der_Herr_der_Ringe_-_Die_R_ckkehr_des_K_nigs.jpg</movie_poster>
	</movie>
	<movie>
		<id>145</id>
		<titel>Simpsons- Der Film</titel>
		<original_title>The Simpsons Movie</original_title>
		<produktionsland>USA</produktionsland>
		<duration>83</duration>
		<release_year>2007</release_year>
		<genre>Zeichentrick</genre>
		<director>David Silverman, Produzent: Matt Groening</director>
		<screenwriter>James L. Brooks, Matt Groening u.a.</screenwriter>
		<music>Hans Zimmer</music>
		<oscars>0</oscars>
		<fsk>ab 6 Jahre</fsk>
		<actors>Synchronstimmen:
Homer Simpson: Norbert Gastell (Dan Castellaneta)
Marge Simpson: Anke Engelke (Julie Kavner)
Bart Simpson: Sandra Schwittau (Nancy Cartwright)
Lisa Simpson: Sabine Bohlmann (Yeardley Smith)
Krusty, der Clown: 	Hans-Rainer Müller (Dan Castellaneta)
Rektor Seymour Skinner: Klaus Guth (Harry Shearer)
Ralph Wiggum: Beate Pfeiffer (Nancy Cartwright)
Ned Flanders: Ulrich Frank (Harry Shearer)</actors>
		<movie_poster>simpsons_movie.jpg</movie_poster>
	</movie>
	<movie>
		<id>146</id>
		<titel>Paranormal Activity 2</titel>
		<original_title>Paranormal Activity 2</original_title>
		<produktionsland>USA</produktionsland>
		<duration>91</duration>
		<release_year>2010</release_year>
		<genre>Horror</genre>
		<director>Tod Williams</director>
		<screenwriter>Michael R. Perry, Christopher B. Landon</screenwriter>
		<music>Michael Simmonds</music>
		<oscars>0</oscars>
		<fsk>ab 16 Jahre</fsk>
		<actors>Micah Sloat: Micah
Katie Featherston: Katie
Brian Boland: Daniel „Dan“ Rey
Sprague Grayden: Kristi Rey
Molly Ephraim: Ali
Tim Clemens: Hunter
</actors>
		<movie_poster>paranormal2_poster_lg.jpg</movie_poster>
	</movie>
	<movie>
		<id>147</id>
		<titel>Der Fluch der Karibik - Teil 1</titel>
		<original_title>Pirates of the Caribbean: The Curse of the Black Pearl</original_title>
		<produktionsland>USA</produktionsland>
		<duration>137</duration>
		<release_year>2003</release_year>
		<genre>Action</genre>
		<director>Gore Verbinski</director>
		<screenwriter>Ted Elliott, Terry Rossio</screenwriter>
		<music>Klaus Badelt</music>
		<oscars>1</oscars>
		<fsk>ab 12 Jahre</fsk>
		<actors>Johnny Depp: Captain Jack Sparrow
Orlando Bloom: William „Will“ Turner
Geoffrey Rush: Captain Hector Barbossa
Keira Knightley: Elizabeth Swann
Jack Davenport: Commodore James Norrington
Jonathan Pryce: Gouverneur Weatherby Swann
Kevin R. McNally: Joshamee Gibbs
Lee Arenberg: Pintel
Mackenzie Crook: Ragetti
Damian O’Hare: Lt. Gillette
Martin Klebba: Marty
David Bailie: Cotton
Zoë Saldaña: Anamaria
Lauren Maher: Scarlett
Vanessa Branch: Giselle</actors>
		<movie_poster>FluchderKaribik-Poster02.jpg</movie_poster>
	</movie>
	<movie>
		<id>148</id>
		<titel>Banana Joe</titel>
		<original_title>Banana Joe</original_title>
		<produktionsland>Italien</produktionsland>
		<duration>96</duration>
		<release_year>1981</release_year>
		<genre>Action</genre>
		<director>Steno (Stefano Vanzina)</director>
		<screenwriter>Bruno Corbucci, Bud Spencer</screenwriter>
		<music>Oliver Onions</music>
		<oscars>0</oscars>
		<fsk>ab 6 Jahre</fsk>
		<actors>Bud Spencer: Banana Joe
Marina Langner: Dorianne
Mario Scarpetta: Manuel
Gianfranco Barra: Torcillo
Enzo Garinei: Moreno
Gunther Philipp: Sarto
Giorgio Bracardi: Martino</actors>
		<movie_poster>banana_joe_spencer.jpg</movie_poster>
	</movie>
	<movie>
		<id>151</id>
		<titel>Zwei Himmelhunde auf dem Weg zur Hölle</titel>
		<original_title>Più forte, ragazzi!</original_title>
		<produktionsland>Italien</produktionsland>
		<duration>102</duration>
		<release_year>1972</release_year>
		<genre>Action</genre>
		<director>Giuseppe Colizzi</director>
		<screenwriter>Barbara Alberti, Giuseppe Colizzi</screenwriter>
		<music>Guido &amp; Maurizio De Angelis </music>
		<oscars>0</oscars>
		<fsk>ab 16 Jahre</fsk>
		<actors>Terence Hill: Plata
Bud Spencer: Salud
Reinhard Kolldehoff: Mr. Ears
Riccardo Pizzuti: Naso
Cyril Cusack: Matto
Alexander Allerson: Saluds Bruder
</actors>
		<movie_poster>zwei_himmelhunde_auf_dem_weg_zur_hoelle.jpg</movie_poster>
	</movie>
	<movie>
		<id>152</id>
		<titel>Matrix</titel>
		<original_title>The Matrix</original_title>
		<produktionsland>USA</produktionsland>
		<duration>131</duration>
		<release_year>1999</release_year>
		<genre>Science-Fiction</genre>
		<director>Wachowski-Geschwister</director>
		<screenwriter>Wachowski-Geschwister</screenwriter>
		<music>Don Davis</music>
		<oscars>4</oscars>
		<fsk>ab 16 Jahre</fsk>
